In [1]:
import os
import glob
import pandas as pd
import numpy as np

curfolder = os.getcwd()
speechcsv = os.path.join(curfolder, 'control_for_speech_check.csv')

df = pd.read_csv(speechcsv)
df

,filename,check,start_time,end_time,has_speech,whisper_text
0,10_1_trial_11_Mic_nominal_srate48000_p1_vuur_c...,no speech,0.0,9.282875,True,Wat is dat?
1,10_1_trial_21_Mic_nominal_srate48000_p0_piepen...,no sound,0.0,9.297125,True,Ik heb het gevoel dat het een beetje te hard is.
2,10_1_trial_23_Mic_nominal_srate48000_p0_vangen...,no sound,0.0,10.808375,True,Wat is dat? Wat is dat?
3,10_1_trial_24_Mic_nominal_srate48000_p0_kauwen...,no sound,0.0,7.720625,True,Dank je wel.
4,10_1_trial_32_Mic_nominal_srate48000_p1_hond_g...,no sound,0.0,5534.000000,True,Dank u wel.
...,...,...,...,...,...,...
1067,9_2_trial_42_Mic_nominal_srate48000_p1_zwemmen...,no speech,0.0,3.998500,True,"Trap, trap, trap."
1068,9_2_trial_49_Mic_nominal_srate48000_p0_goed_co...,no speech,0.0,2497.000000,True,Mmm.
1069,9_2_trial_56_Mic_nominal_srate48000_p0_gooien_...,speech? Yes,0.0,3.477688,True,Vans.
1070,9_2_trial_57_Mic_nominal_srate48000_p0_water_c...,no speech,0.0,3.194187,True,Dank u wel.
1071,9_2_trial_63_Mic_nominal_srate48000_p1_ik_comb...,speech? Ik,0.0,1.995812,True,Dank u wel.

In [2]:
# get rid of rows where check == no speech
df = df[df['check'] != 'no speech']
df

,filename,check,start_time,end_time,has_speech,whisper_text
1,10_1_trial_21_Mic_nominal_srate48000_p0_piepen...,no sound,0.0,9.297125,True,Ik heb het gevoel dat het een beetje te hard is.
2,10_1_trial_23_Mic_nominal_srate48000_p0_vangen...,no sound,0.0,10.808375,True,Wat is dat? Wat is dat?
3,10_1_trial_24_Mic_nominal_srate48000_p0_kauwen...,no sound,0.0,7.720625,True,Dank je wel.
4,10_1_trial_32_Mic_nominal_srate48000_p1_hond_g...,no sound,0.0,5534.000000,True,Dank u wel.
5,10_1_trial_33_Mic_nominal_srate48000_p1_ei_geb...,no sound,0.0,6.586938,True,Dank u wel.
...,...,...,...,...,...,...
1062,9_1_trial_43_Mic_nominal_srate48000_p0_staan_c...,speech? Ja,0.0,5.199187,True,Dank u wel.
1064,9_2_trial_104_Mic_nominal_srate48000_p1_hond_g...,no sound,0.0,3.206313,True,Dank u wel.
1065,9_2_trial_109_Mic_nominal_srate48000_p1_niet_g...,no sound,0.0,13.349187,True,Dank u wel. ***
1069,9_2_trial_56_Mic_nominal_srate48000_p0_gooien_...,speech? Yes,0.0,3.477688,True,Vans.
1071,9_2_trial_63_Mic_nominal_srate48000_p1_ik_comb...,speech? Ik,0.0,1.995812,True,Dank u wel.

In [3]:
# get rid of rows where check == no sound
df = df[df['check'] != 'no sound']
df

,filename,check,start_time,end_time,has_speech,whisper_text
135,17_2_trial_53_Mic_nominal_srate48000_p0_vliege...,"Laughing, long time no sound",0.0,18.741250,True,Ja. Ja. Ja. Ja. Ja.
159,19_1_trial_21_Mic_nominal_srate48000_p0_vrouw_...,speech cut,0.0,5.699937,True,Uw vrouw.
160,19_1_trial_3_Mic_nominal_srate48000_p0_hond_ge...,noisy,0.0,3.891250,True,"Moef, moef."
161,19_1_trial_7_Mic_nominal_srate48000_p0_vangen_...,Laugh,0.0,4.372625,True,Oeh.
163,19_2_trial_15_Mic_nominal_srate48000_p0_niet_g...,noisy (breathing at the end),0.0,5.376875,True,Dank je wel.
...,...,...,...,...,...,...
1012,72_2_trial_78_Mic_nominal_srate48000_p1_staart...,speech,0.0,5.740500,True,"Wouf, wouf."
1018,7_1_trial_15_Mic_nominal_srate48000_p1_langzaa...,speech,0.0,9.799250,True,Wat is dat?
1062,9_1_trial_43_Mic_nominal_srate48000_p0_staan_c...,speech? Ja,0.0,5.199187,True,Dank u wel.
1069,9_2_trial_56_Mic_nominal_srate48000_p0_gooien_...,speech? Yes,0.0,3.477688,True,Vans.
1071,9_2_trial_63_Mic_nominal_srate48000_p1_ik_comb...,speech? Ik,0.0,1.995812,True,Dank u wel.

In [8]:
# get rid of rows that contain string noisy or onisy
df = df[~df['check'].str.contains('noisy', case=False, na=False)]
df

df = df[~df['check'].str.contains('onisy', case=False, na=False)]
df

,filename,check,start_time,end_time,has_speech,whisper_text
159,19_1_trial_21_Mic_nominal_srate48000_p0_vrouw_...,speech cut,0.0,5.699937,True,Uw vrouw.
176,20_1_trial_16_Mic_nominal_srate48000_p1_kauwen...,speech? Ja,0.0,9.825875,True,Ik heb het gevoel dat ik een vrouw ben.
177,20_1_trial_17_Mic_nominal_srate48000_p1_slaan_...,speech?,0.0,5.242625,True,Kut.
190,20_2_trial_42_Mic_nominal_srate48000_p1_spring...,speech,0.0,10.173562,True,Wat is dat? ***
197,20_2_trial_66_Mic_nominal_srate48000_p1_blij_c...,speech,0.0,8.846187,True,Ik ga even kijken.
224,24_1_trial_40_Mic_nominal_srate48000_p0_scherp...,speech at the end?,0.0,5.606250,True,Wat is dat?
230,24_2_trial_27_Mic_nominal_srate48000_p1_bitter...,?,0.0,2.255375,True,Doe het goed.
256,26_2_trial_55_Mic_nominal_srate48000_p0_verbra...,speech,0.0,9.645938,True,Oud.
260,26_2_trial_6_Mic_nominal_srate48000_p0_kind_ge...,speech?,0.0,6.538687,True,Dank je wel voor het kijken.
264,27_1_trial_11_Mic_nominal_srate48000_p1_ik_com...,speech cut,0.0,21.121625,True,Dank u wel. *** ***
291,27_2_trial_95_Mic_nominal_srate48000_p1_stil_g...,speech?,0.0,13.039062,True,Mooi. ***
295,28_2_trial_33_Mic_nominal_srate48000_p0_bang_g...,speech,0.0,3.037313,True,"Oh, oh, oh."
349,30_2_trial_103_Mic_nominal_srate48000_p1_staar...,speech,0.0,13.763063,True,Dank u wel. Yes. Yes. Yes.
354,30_2_trial_30_Mic_nominal_srate48000_p1_kind_g...,"speech? mama, papa",0.0,4.209750,True,Mama. Papa.
355,30_2_trial_31_Mic_nominal_srate48000_p1_kind_g...,speech? mama papa,0.0,7.981438,True,Moema. Moema.
358,30_2_trial_47_Mic_nominal_srate48000_p0_hoorn_...,speech,0.0,8.108813,True,Sssst.
369,30_2_trial_83_Mic_nominal_srate48000_p0_vlieg_...,speech at the beginning,0.0,10.696875,True,Ja. ***
371,30_2_trial_98_Mic_nominal_srate48000_p1_geur_c...,speech,0.0,20.732125,True,Ik ben een vrouw. ZANG EN MUZIEK ZANG EN MUZIEK
481,37_1_trial_14_Mic_nominal_srate48000_p1_oud_ge...,speech,0.0,12.010625,True,Ik ben er. Ah.
482,37_1_trial_21_Mic_nominal_srate48000_p0_kind_g...,speech,0.0,3.791313,True,Naar de schoen.
485,37_2_trial_104_Mic_nominal_srate48000_p1_bitte...,low,0.0,21.876625,True,Dank u wel. *** ***
486,37_2_trial_105_Mic_nominal_srate48000_p1_bitte...,low,0.0,14.133625,True,Dank u wel. ***
488,37_2_trial_27_Mic_nominal_srate48000_p1_scherp...,speech,0.0,10.886062,True,Dank u wel. ***
508,39_2_trial_31_Mic_nominal_srate48000_p1_kind_g...,speech,0.0,14.951625,True,Ah. Ah. Ah. Ah. Ah. Ah.
590,46_2_trial_55_Mic_nominal_srate48000_p1_bitter...,speech,0.0,6.402750,True,Dank u wel.
608,4_1_trial_47_Mic_nominal_srate48000_p1_boos_ge...,check video,0.0,2.667250,True,Dank u wel.
630,51_2_trial_30_Mic_nominal_srate48000_p1_ik_gel...,cat sounds??,0.0,7.715687,True,Mooi. Mooi.
675,55_2_trial_92_Mic_nominal_srate48000_p0_blij_c...,speech?,0.0,3.856187,True,Oeh.
676,55_2_trial_93_Mic_nominal_srate48000_p0_blij_c...,speech?,0.0,5.294812,True,Hmmmmmmmmmmmmmmmm.
682,56_2_trial_32_Mic_nominal_srate48000_p1_luidru...,speech?,0.0,5.721687,True,Deze film is geïnteresseerd door het Oude Westen.
684,56_2_trial_61_Mic_nominal_srate48000_p0_jagen_...,speech,0.0,5.014375,True,Daag.
710,57_2_trial_9_Mic_nominal_srate48000_p0_blij_co...,speech?,0.0,3.125250,True,Hmm.
723,59_2_trial_15_Mic_nominal_srate48000_p1_vogel_...,low,0.0,4.240500,True,"Klaar, klaar, klaar, klaar, klaar, klaar."
726,59_2_trial_67_Mic_nominal_srate48000_p1_water_...,low,0.0,16.261813,True,Dank u wel. ***
760,5_2_trial_74_Mic_nominal_srate48000_p0_man_gel...,is bla?,0.0,4.595562,True,Deze is de eerste.
794,61_1_trial_16_Mic_nominal_srate48000_p1_lachen...,low,0.0,3.193687,True,Dank u wel.
800,61_2_trial_14_Mic_nominal_srate48000_p0_jagen_...,speech,0.0,20.596187,True,Ja. Ja. Ja.
813,61_2_trial_84_Mic_nominal_srate48000_p0_sterk_...,speech?,0.0,14.854500,True,Oefen. Oefen.
843,62_2_trial_40_Mic_nominal_srate48000_p0_bitter...,speech,0.0,19.940062,True,Dank u wel. ***
861,63_1_trial_38_Mic_nominal_srate48000_p0_kind_g...,speech,0.0,6.992063,True,"Wauw, wauw."
872,64_1_trial_20_Mic_nominal_srate48000_p0_kat_co...,speech,0.0,4.523313,True,Ja.
873,64_1_trial_4_Mic_nominal_srate48000_p0_ei_gelu...,speech,0.0,13129.000000,True,Oké. Oké.
905,66_2_trial_104_Mic_nominal_srate48000_p1_jagen...,low,0.0,9.984937,True,Hmm.
920,67_2_trial_44_Mic_nominal_srate48000_p1_jagen_...,speech?,0.0,4444.000000,True,Oké. Kats.
956,6_2_trial_103_Mic_nominal_srate48000_p1_zoet_g...,speech,0.0,5.471063,True,Ik ga even kijken.
979,6_2_trial_96_Mic_nominal_srate48000_p0_gooien_...,no speech/sound,0.0,4.621500,True,Ik weet niet waarom ik hier ben.
991,70_2_trial_79_Mic_nominal_srate48000_p0_hoorn_...,speech,0.0,11.482812,True,Ik ben er. Dank u wel.
994,71_2_trial_47_Mic_nominal_srate48000_p0_bang_g...,speech? name of the word,0.0,3.573375,True,Goed.
995,71_2_trial_60_Mic_nominal_srate48000_p1_bitter...,speech,0.0,3.271500,True,En...
1012,72_2_trial_78_Mic_nominal_srate48000_p1_staart...,speech,0.0,5.740500,True,"Wouf, wouf."
1018,7_1_trial_15_Mic_nominal_srate48000_p1_langzaa...,speech,0.0,9.799250,True,Wat is dat?
1062,9_1_trial_43_Mic_nominal_srate48000_p0_staan_c...,speech? Ja,0.0,5.199187,True,Dank u wel.
1069,9_2_trial_56_Mic_nominal_srate48000_p0_gooien_...,speech? Yes,0.0,3.477688,True,Vans.
1071,9_2_trial_63_Mic_nominal_srate48000_p1_ik_comb...,speech? Ik,0.0,1.995812,True,Dank u wel.

In [9]:
# get rid of rows that contain laugh or Laugh string
df = df[~df['check'].str.contains('laugh', case=False, na=False)]
df

,filename,check,start_time,end_time,has_speech,whisper_text
159,19_1_trial_21_Mic_nominal_srate48000_p0_vrouw_...,speech cut,0.0,5.699937,True,Uw vrouw.
176,20_1_trial_16_Mic_nominal_srate48000_p1_kauwen...,speech? Ja,0.0,9.825875,True,Ik heb het gevoel dat ik een vrouw ben.
177,20_1_trial_17_Mic_nominal_srate48000_p1_slaan_...,speech?,0.0,5.242625,True,Kut.
190,20_2_trial_42_Mic_nominal_srate48000_p1_spring...,speech,0.0,10.173562,True,Wat is dat? ***
197,20_2_trial_66_Mic_nominal_srate48000_p1_blij_c...,speech,0.0,8.846187,True,Ik ga even kijken.
224,24_1_trial_40_Mic_nominal_srate48000_p0_scherp...,speech at the end?,0.0,5.606250,True,Wat is dat?
230,24_2_trial_27_Mic_nominal_srate48000_p1_bitter...,?,0.0,2.255375,True,Doe het goed.
256,26_2_trial_55_Mic_nominal_srate48000_p0_verbra...,speech,0.0,9.645938,True,Oud.
260,26_2_trial_6_Mic_nominal_srate48000_p0_kind_ge...,speech?,0.0,6.538687,True,Dank je wel voor het kijken.
264,27_1_trial_11_Mic_nominal_srate48000_p1_ik_com...,speech cut,0.0,21.121625,True,Dank u wel. *** ***
291,27_2_trial_95_Mic_nominal_srate48000_p1_stil_g...,speech?,0.0,13.039062,True,Mooi. ***
295,28_2_trial_33_Mic_nominal_srate48000_p0_bang_g...,speech,0.0,3.037313,True,"Oh, oh, oh."
349,30_2_trial_103_Mic_nominal_srate48000_p1_staar...,speech,0.0,13.763063,True,Dank u wel. Yes. Yes. Yes.
354,30_2_trial_30_Mic_nominal_srate48000_p1_kind_g...,"speech? mama, papa",0.0,4.209750,True,Mama. Papa.
355,30_2_trial_31_Mic_nominal_srate48000_p1_kind_g...,speech? mama papa,0.0,7.981438,True,Moema. Moema.
358,30_2_trial_47_Mic_nominal_srate48000_p0_hoorn_...,speech,0.0,8.108813,True,Sssst.
369,30_2_trial_83_Mic_nominal_srate48000_p0_vlieg_...,speech at the beginning,0.0,10.696875,True,Ja. ***
371,30_2_trial_98_Mic_nominal_srate48000_p1_geur_c...,speech,0.0,20.732125,True,Ik ben een vrouw. ZANG EN MUZIEK ZANG EN MUZIEK
481,37_1_trial_14_Mic_nominal_srate48000_p1_oud_ge...,speech,0.0,12.010625,True,Ik ben er. Ah.
482,37_1_trial_21_Mic_nominal_srate48000_p0_kind_g...,speech,0.0,3.791313,True,Naar de schoen.
485,37_2_trial_104_Mic_nominal_srate48000_p1_bitte...,low,0.0,21.876625,True,Dank u wel. *** ***
486,37_2_trial_105_Mic_nominal_srate48000_p1_bitte...,low,0.0,14.133625,True,Dank u wel. ***
488,37_2_trial_27_Mic_nominal_srate48000_p1_scherp...,speech,0.0,10.886062,True,Dank u wel. ***
508,39_2_trial_31_Mic_nominal_srate48000_p1_kind_g...,speech,0.0,14.951625,True,Ah. Ah. Ah. Ah. Ah. Ah.
590,46_2_trial_55_Mic_nominal_srate48000_p1_bitter...,speech,0.0,6.402750,True,Dank u wel.
608,4_1_trial_47_Mic_nominal_srate48000_p1_boos_ge...,check video,0.0,2.667250,True,Dank u wel.
630,51_2_trial_30_Mic_nominal_srate48000_p1_ik_gel...,cat sounds??,0.0,7.715687,True,Mooi. Mooi.
675,55_2_trial_92_Mic_nominal_srate48000_p0_blij_c...,speech?,0.0,3.856187,True,Oeh.
676,55_2_trial_93_Mic_nominal_srate48000_p0_blij_c...,speech?,0.0,5.294812,True,Hmmmmmmmmmmmmmmmm.
682,56_2_trial_32_Mic_nominal_srate48000_p1_luidru...,speech?,0.0,5.721687,True,Deze film is geïnteresseerd door het Oude Westen.
684,56_2_trial_61_Mic_nominal_srate48000_p0_jagen_...,speech,0.0,5.014375,True,Daag.
710,57_2_trial_9_Mic_nominal_srate48000_p0_blij_co...,speech?,0.0,3.125250,True,Hmm.
723,59_2_trial_15_Mic_nominal_srate48000_p1_vogel_...,low,0.0,4.240500,True,"Klaar, klaar, klaar, klaar, klaar, klaar."
726,59_2_trial_67_Mic_nominal_srate48000_p1_water_...,low,0.0,16.261813,True,Dank u wel. ***
760,5_2_trial_74_Mic_nominal_srate48000_p0_man_gel...,is bla?,0.0,4.595562,True,Deze is de eerste.
794,61_1_trial_16_Mic_nominal_srate48000_p1_lachen...,low,0.0,3.193687,True,Dank u wel.
800,61_2_trial_14_Mic_nominal_srate48000_p0_jagen_...,speech,0.0,20.596187,True,Ja. Ja. Ja.
813,61_2_trial_84_Mic_nominal_srate48000_p0_sterk_...,speech?,0.0,14.854500,True,Oefen. Oefen.
843,62_2_trial_40_Mic_nominal_srate48000_p0_bitter...,speech,0.0,19.940062,True,Dank u wel. ***
861,63_1_trial_38_Mic_nominal_srate48000_p0_kind_g...,speech,0.0,6.992063,True,"Wauw, wauw."
872,64_1_trial_20_Mic_nominal_srate48000_p0_kat_co...,speech,0.0,4.523313,True,Ja.
873,64_1_trial_4_Mic_nominal_srate48000_p0_ei_gelu...,speech,0.0,13129.000000,True,Oké. Oké.
905,66_2_trial_104_Mic_nominal_srate48000_p1_jagen...,low,0.0,9.984937,True,Hmm.
920,67_2_trial_44_Mic_nominal_srate48000_p1_jagen_...,speech?,0.0,4444.000000,True,Oké. Kats.
956,6_2_trial_103_Mic_nominal_srate48000_p1_zoet_g...,speech,0.0,5.471063,True,Ik ga even kijken.
979,6_2_trial_96_Mic_nominal_srate48000_p0_gooien_...,no speech/sound,0.0,4.621500,True,Ik weet niet waarom ik hier ben.
991,70_2_trial_79_Mic_nominal_srate48000_p0_hoorn_...,speech,0.0,11.482812,True,Ik ben er. Dank u wel.
994,71_2_trial_47_Mic_nominal_srate48000_p0_bang_g...,speech? name of the word,0.0,3.573375,True,Goed.
995,71_2_trial_60_Mic_nominal_srate48000_p1_bitter...,speech,0.0,3.271500,True,En...
1012,72_2_trial_78_Mic_nominal_srate48000_p1_staart...,speech,0.0,5.740500,True,"Wouf, wouf."
1018,7_1_trial_15_Mic_nominal_srate48000_p1_langzaa...,speech,0.0,9.799250,True,Wat is dat?
1062,9_1_trial_43_Mic_nominal_srate48000_p0_staan_c...,speech? Ja,0.0,5.199187,True,Dank u wel.
1069,9_2_trial_56_Mic_nominal_srate48000_p0_gooien_...,speech? Yes,0.0,3.477688,True,Vans.
1071,9_2_trial_63_Mic_nominal_srate48000_p1_ik_comb...,speech? Ik,0.0,1.995812,True,Dank u wel.

In [10]:
# save this
df.to_csv(os.path.join(curfolder, 'control_for_speech_check_cleaned.csv'), index=False)

In [11]:
# load back in
df = pd.read_csv(os.path.join(curfolder, 'control_for_speech_check_cleaned.csv'))

# get rid of all rows containing no speech string
df = df[~df['check'].str.contains('no speech', case=False, na=False)]
df

,filename,check,start_time,end_time,has_speech,whisper_text
0,19_1_trial_21_Mic_nominal_srate48000_p0_vrouw_...,speech but condition broken,0.0,5.699937,True,Uw vrouw.
3,20_2_trial_42_Mic_nominal_srate48000_p1_spring...,can be cut,0.0,10.173562,True,Wat is dat? ***
5,24_1_trial_40_Mic_nominal_srate48000_p0_scherp...,can be cut,0.0,5.606250,True,Wat is dat?
7,26_2_trial_55_Mic_nominal_srate48000_p0_verbra...,can be cut,0.0,9.645938,True,Oud.
8,26_2_trial_6_Mic_nominal_srate48000_p0_kind_ge...,"speech (papa, mama)",0.0,6.538687,True,Dank je wel voor het kijken.
9,27_1_trial_11_Mic_nominal_srate48000_p1_ik_com...,speech,0.0,21.121625,True,Dank u wel. *** ***
11,28_2_trial_33_Mic_nominal_srate48000_p0_bang_g...,can be probably cut,0.0,3.037313,True,"Oh, oh, oh."
12,30_2_trial_103_Mic_nominal_srate48000_p1_staar...,interrupted in the middle,0.0,13.763063,True,Dank u wel. Yes. Yes. Yes.
13,30_2_trial_30_Mic_nominal_srate48000_p1_kind_g...,"speech (papa, mama)",0.0,4.209750,True,Mama. Papa.
14,30_2_trial_31_Mic_nominal_srate48000_p1_kind_g...,"speech (papa, mama)",0.0,7.981438,True,Moema. Moema.
15,30_2_trial_47_Mic_nominal_srate48000_p0_hoorn_...,can be cut,0.0,8.108813,True,Sssst.
16,30_2_trial_83_Mic_nominal_srate48000_p0_vlieg_...,can be cut,0.0,10.696875,True,Ja. ***
17,30_2_trial_98_Mic_nominal_srate48000_p1_geur_c...,can be probably cut,0.0,20.732125,True,Ik ben een vrouw. ZANG EN MUZIEK ZANG EN MUZIEK
18,37_1_trial_14_Mic_nominal_srate48000_p1_oud_ge...,can be cut,0.0,12.010625,True,Ik ben er. Ah.
19,37_1_trial_21_Mic_nominal_srate48000_p0_kind_g...,speech,0.0,3.791313,True,Naar de schoen.
20,37_2_trial_104_Mic_nominal_srate48000_p1_bitte...,ja in the end,0.0,21.876625,True,Dank u wel. *** ***
21,37_2_trial_105_Mic_nominal_srate48000_p1_bitte...,the same,0.0,14.133625,True,Dank u wel. ***
22,37_2_trial_27_Mic_nominal_srate48000_p1_scherp...,condition broke,0.0,10.886062,True,Dank u wel. ***
23,39_2_trial_31_Mic_nominal_srate48000_p1_kind_g...,can be cut,0.0,14.951625,True,Ah. Ah. Ah. Ah. Ah. Ah.
30,56_2_trial_61_Mic_nominal_srate48000_p0_jagen_...,condition broke,0.0,5.014375,True,Daag.
36,61_2_trial_14_Mic_nominal_srate48000_p0_jagen_...,speech (okay okay),0.0,20.596187,True,Ja. Ja. Ja.
37,61_2_trial_84_Mic_nominal_srate48000_p0_sterk_...,condition broke,0.0,14.854500,True,Oefen. Oefen.
39,63_1_trial_38_Mic_nominal_srate48000_p0_kind_g...,can be cut,0.0,6.992063,True,"Wauw, wauw."
40,64_1_trial_20_Mic_nominal_srate48000_p0_kat_co...,can be cut,0.0,4.523313,True,Ja.
41,64_1_trial_4_Mic_nominal_srate48000_p0_ei_gelu...,condition broke,0.0,13129.000000,True,Oké. Oké.
42,66_2_trial_104_Mic_nominal_srate48000_p1_jagen...,condition broke? (walking?),0.0,9.984937,True,Hmm.
43,67_2_trial_44_Mic_nominal_srate48000_p1_jagen_...,condition broke?,0.0,4444.000000,True,Oké. Kats.
44,6_2_trial_103_Mic_nominal_srate48000_p1_zoet_g...,condition broke,0.0,5.471063,True,Ik ga even kijken.
46,70_2_trial_79_Mic_nominal_srate48000_p0_hoorn_...,condition broke,0.0,11.482812,True,Ik ben er. Dank u wel.
49,72_2_trial_78_Mic_nominal_srate48000_p1_staart...,can be cut,0.0,5.740500,True,"Wouf, wouf."
50,7_1_trial_15_Mic_nominal_srate48000_p1_langzaa...,condition broke,0.0,9.799250,True,Wat is dat?
52,9_2_trial_56_Mic_nominal_srate48000_p0_gooien_...,speech? Yes,0.0,3.477688,True,Vans.
53,9_2_trial_63_Mic_nominal_srate48000_p1_ik_comb...,speech,0.0,1.995812,True,Dank u wel.